class_name LocalStrikeWeaponCatalog
extends RefCounted

const Definition = preload("res://scripts/weapon_definition.gd")

static var _weapons: Dictionary = {}

static func all() -> Dictionary:
	if _weapons.is_empty():
		_build()
	return _weapons

static func get_weapon(key: String) -> LocalStrikeWeaponDefinition:
	return all().get(key, all()["sidearm"])

static func primary_keys() -> Array[String]:
	return ["smg", "whisper", "ranger", "sentinel", "hammer", "breacher", "cyclone", "doublebarrel", "marksman", "longbow", "heavy_sniper", "bulwark"]

static func secondary_keys() -> Array[String]:
	return ["sidearm", "vanguard", "kestrel"]

static func melee_keys() -> Array[String]:
	return ["knife", "machete", "baseball_bat", "crowbar", "fire_axe", "sledgehammer"]

static func bot_weapon_keys() -> Array[String]:
	return secondary_keys() + primary_keys() + melee_keys()

static func sandbox_weapon_keys() -> Array[String]:
	return melee_keys() + secondary_keys() + primary_keys() + ["frag", "smoke", "flash", "incendiary"]

static func _build() -> void:
	_weapons = {
		"kestrel": Definition.create({"key": "kestrel", "display_name": "KESTREL AUTO PISTOL", "slot": Definition.Slot.SECONDARY, "price": 900, "damage": 18.0, "head_multiplier": 3.0, "spread": 0.025, "move_spread": 0.035, "range": 30.0, "magazine": 20, "reserve": 80, "fire_delay": 0.07, "reload_time": 1.45, "fire_modes": ["auto", "semi"], "recoil_pattern": [Vector2(-0.009, 0.017), Vector2(0.013, 0.021), Vector2(-0.016, 0.025), Vector2(0.019, 0.028)], "category": "pistol", "penetration_power": 0.32, "armor_penetration": 0.38, "falloff_start": 9.0, "falloff_end": 30.0, "minimum_damage_multiplier": 0.42, "ads_fov": 66.0, "weight": 0.82, "sound_profile": "pistol"}),
		"doublebarrel": Definition.create({"key": "doublebarrel", "display_name": "OUTLAW DOUBLE BARREL", "price": 1600, "damage": 14.0, "head_multiplier": 1.3, "spread": 0.105, "move_spread": 0.05, "range": 16.0, "magazine": 2, "reserve": 30, "fire_delay": 0.24, "reload_time": 2.35, "pellets": 10, "automatic": false, "fire_modes": ["semi"], "recoil_pattern": [Vector2(-0.012, 0.085), Vector2(0.016, 0.095)], "category": "shotgun", "penetration_power": 0.25, "armor_penetration": 0.28, "falloff_start": 4.0, "falloff_end": 17.0, "minimum_damage_multiplier": 0.22, "ads_fov": 65.0, "weight": 0.95, "shot_impulse": 8.0, "sound_profile": "shotgun"}),
		"longbow": Definition.create({"key": "longbow", "display_name": "LONGBOW SCOUT", "price": 2200, "damage": 68.0, "head_multiplier": 2.6, "spread": 0.003, "move_spread": 0.06, "range": 95.0, "magazine": 8, "reserve": 32, "fire_delay": 0.9, "reload_time": 1.7, "automatic": false, "fire_modes": ["bolt"], "recoil_pattern": [Vector2(0.006, 0.048), Vector2(-0.008, 0.052)], "category": "sniper", "penetration_power": 1.2, "armor_penetration": 0.76, "falloff_start": 45.0, "falloff_end": 100.0, "minimum_damage_multiplier": 0.75, "ads_fov": 32.0, "weight": 0.9, "shot_impulse": 5.0, "sound_profile": "sniper"}),
		"knife": Definition.create({"key": "knife", "display_name": "COMBAT KNIFE", "slot": Definition.Slot.MELEE, "damage": 38.0, "range": 1.95, "magazine": 1, "reserve": 0, "fire_delay": 0.38, "reload_time": 0.0, "automatic": false, "fire_modes": ["melee"], "recoil_pitch": 0.0, "recoil_yaw": 0.0, "category": "knife", "penetration_power": 0.0, "weight": 0.72, "melee_type": "sharp", "melee_reach": 1.95, "melee_arc_degrees": 64.0, "melee_light_damage": 38.0, "melee_heavy_damage": 72.0, "melee_light_recovery": 0.38, "melee_heavy_recovery": 0.72, "melee_max_targets": 2, "melee_impulse": 5.5, "blood_multiplier": 1.0}),
		"machete": Definition.create({"key": "machete", "display_name": "MACHETE", "slot": Definition.Slot.MELEE, "damage": 58.0, "range": 2.25, "magazine": 1, "reserve": 0, "fire_delay": 0.56, "reload_time": 0.0, "automatic": false, "fire_modes": ["melee"], "category": "machete", "weight": 0.92, "melee_type": "sharp", "melee_reach": 2.25, "melee_arc_degrees": 82.0, "melee_light_damage": 58.0, "melee_heavy_damage": 105.0, "melee_light_recovery": 0.56, "melee_heavy_recovery": 0.9, "melee_max_targets": 2, "melee_impulse": 7.0, "blood_multiplier": 1.5}),
		"baseball_bat": Definition.create({"key": "baseball_bat", "display_name": "BASEBALL BAT", "slot": Definition.Slot.MELEE, "damage": 44.0, "range": 2.3, "magazine": 1, "reserve": 0, "fire_delay": 0.62, "reload_time": 0.0, "automatic": false, "fire_modes": ["melee"], "category": "baseball_bat", "weight": 1.0, "melee_type": "blunt", "melee_reach": 2.3, "melee_arc_degrees": 96.0, "melee_light_damage": 44.0, "melee_heavy_damage": 80.0, "melee_light_recovery": 0.62, "melee_heavy_recovery": 0.96, "melee_max_targets": 3, "melee_impulse": 12.0, "blood_multiplier": 0.78}),
		"crowbar": Definition.create({"key": "crowbar", "display_name": "CROWBAR", "slot": Definition.Slot.MELEE, "damage": 50.0, "range": 2.1, "magazine": 1, "reserve": 0, "fire_delay": 0.56, "reload_time": 0.0, "automatic": false, "fire_modes": ["melee"], "category": "crowbar", "weight": 0.9, "melee_type": "blunt", "melee_reach": 2.1, "melee_arc_degrees": 78.0, "melee_light_damage": 50.0, "melee_heavy_damage": 88.0, "melee_light_recovery": 0.56, "melee_heavy_recovery": 0.9, "melee_max_targets": 2, "melee_impulse": 10.0, "blood_multiplier": 0.9}),
		"fire_axe": Definition.create({"key": "fire_axe", "display_name": "FIRE AXE", "slot": Definition.Slot.MELEE, "damage": 72.0, "range": 2.2, "magazine": 1, "reserve": 0, "fire_delay": 0.82, "reload_time": 0.0, "automatic": false, "fire_modes": ["melee"], "category": "fire_axe", "weight": 1.18, "melee_type": "sharp", "melee_reach": 2.2, "melee_arc_degrees": 72.0, "melee_light_damage": 72.0, "melee_heavy_damage": 130.0, "melee_light_recovery": 0.82, "melee_heavy_recovery": 1.22, "melee_max_targets": 2, "melee_impulse": 14.0, "blood_multiplier": 1.8}),
		"sledgehammer": Definition.create({"key": "sledgehammer", "display_name": "SLEDGEHAMMER", "slot": Definition.Slot.MELEE, "damage": 84.0, "range": 2.35, "magazine": 1, "reserve": 0, "fire_delay": 1.0, "reload_time": 0.0, "automatic": false, "fire_modes": ["melee"], "category": "sledgehammer", "weight": 1.38, "melee_type": "blunt", "melee_reach": 2.35, "melee_arc_degrees": 68.0, "melee_light_damage": 84.0, "melee_heavy_damage": 150.0, "melee_light_recovery": 1.0, "melee_heavy_recovery": 1.45, "melee_max_targets": 3, "melee_impulse": 20.0, "blood_multiplier": 1.1}),
		"sidearm": Definition.create({"key": "sidearm", "display_name": "SIDEARM", "slot": Definition.Slot.SECONDARY, "damage": 34.0, "head_multiplier": 3.8, "spread": 0.011, "move_spread": 0.022, "range": 38.0, "magazine": 12, "reserve": 36, "fire_delay": 0.28, "reload_time": 1.05, "automatic": false, "fire_modes": ["semi"], "recoil_pattern": [Vector2(0.0, 0.024), Vector2(0.009, 0.027), Vector2(-0.008, 0.03)], "category": "pistol", "penetration_power": 0.48, "armor_penetration": 0.48, "ads_fov": 66.0, "sound_profile": "pistol"}),
		"vanguard": Definition.create({"key": "vanguard", "display_name": "VANGUARD REVOLVER", "slot": Definition.Slot.SECONDARY, "price": 700, "damage": 54.0, "head_multiplier": 2.4, "spread": 0.009, "move_spread": 0.032, "range": 48.0, "magazine": 6, "reserve": 24, "fire_delay": 0.42, "reload_time": 1.9, "automatic": false, "fire_modes": ["semi"], "recoil_pattern": [Vector2(0.012, 0.052), Vector2(-0.014, 0.056), Vector2(0.008, 0.06)], "category": "revolver", "penetration_power": 0.82, "armor_penetration": 0.72, "ads_fov": 64.0, "shot_impulse": 5.4, "sound_profile": "revolver"}),
		"smg": Definition.create({"key": "smg", "display_name": "COMPACT SMG", "price": 1250, "damage": 22.0, "head_multiplier": 3.0, "spread": 0.024, "move_spread": 0.035, "range": 32.0, "magazine": 30, "reserve": 90, "fire_delay": 0.075, "reload_time": 1.35, "recoil_pattern": [Vector2(-0.004, 0.012), Vector2(0.006, 0.014), Vector2(-0.008, 0.016), Vector2(0.009, 0.017)], "category": "smg", "penetration_power": 0.46, "armor_penetration": 0.44, "ads_fov": 64.0, "sound_profile": "smg"}),
		"whisper": Definition.create({"key": "whisper", "display_name": "WHISPER SMG", "price": 1800, "damage": 20.0, "head_multiplier": 3.2, "spread": 0.018, "move_spread": 0.03, "range": 38.0, "magazine": 30, "reserve": 90, "fire_delay": 0.082, "reload_time": 1.45, "recoil_pattern": [Vector2(-0.003, 0.01), Vector2(0.004, 0.012), Vector2(0.006, 0.013), Vector2(-0.005, 0.014)], "category": "suppressed_smg", "penetration_power": 0.42, "armor_penetration": 0.46, "ads_fov": 62.0, "sound_profile": "suppressed"}),
		"ranger": Definition.create({"key": "ranger", "display_name": "RANGER RIFLE", "price": 2700, "damage": 31.0, "head_multiplier": 3.6, "spread": 0.017, "move_spread": 0.038, "range": 58.0, "magazine": 30, "reserve": 90, "fire_delay": 0.095, "reload_time": 1.55, "recoil_pattern": [Vector2(-0.006, 0.019), Vector2(0.009, 0.021), Vector2(0.012, 0.024), Vector2(-0.014, 0.026), Vector2(-0.008, 0.028)], "category": "rifle", "penetration_power": 0.92, "armor_penetration": 0.68, "falloff_start": 24.0, "falloff_end": 62.0}),
		"sentinel": Definition.create({"key": "sentinel", "display_name": "SENTINEL CARBINE", "price": 2400, "damage": 28.0, "head_multiplier": 3.5, "spread": 0.013, "move_spread": 0.03, "range": 56.0, "magazine": 25, "reserve": 75, "fire_delay": 0.09, "reload_time": 1.48, "fire_modes": ["auto", "semi"], "recoil_pattern": [Vector2(-0.004, 0.015), Vector2(0.006, 0.017), Vector2(0.008, 0.019), Vector2(-0.009, 0.021)], "category": "carbine", "penetration_power": 0.82, "armor_penetration": 0.64, "ads_fov": 58.0}),
		"hammer": Definition.create({"key": "hammer", "display_name": "HAMMER BATTLE RIFLE", "price": 3400, "damage": 43.0, "head_multiplier": 2.8, "spread": 0.011, "move_spread": 0.046, "range": 68.0, "magazine": 20, "reserve": 60, "fire_delay": 0.13, "reload_time": 1.8, "fire_modes": ["semi", "auto"], "recoil_pattern": [Vector2(0.009, 0.036), Vector2(-0.012, 0.041), Vector2(0.015, 0.046), Vector2(-0.018, 0.05)], "category": "battle_rifle", "penetration_power": 1.42, "armor_penetration": 0.82, "ads_fov": 55.0, "weight": 1.22, "shot_impulse": 5.2}),
		"breacher": Definition.create({"key": "breacher", "display_name": "BREACHER", "price": 2100, "damage": 16.0, "head_multiplier": 1.45, "spread": 0.095, "move_spread": 0.045, "range": 18.0, "magazine": 6, "reserve": 30, "fire_delay": 0.68, "reload_time": 1.65, "pellets": 7, "automatic": false, "fire_modes": ["pump"], "recoil_pattern": [Vector2(0.0, 0.07)], "category": "shotgun", "penetration_power": 0.38, "armor_penetration": 0.34, "ads_fov": 64.0, "shot_impulse": 7.0}),
		"cyclone": Definition.create({"key": "cyclone", "display_name": "CYCLONE AUTO-SHOTGUN", "price": 3200, "damage": 11.0, "head_multiplier": 1.4, "spread": 0.082, "move_spread": 0.05, "range": 20.0, "magazine": 8, "reserve": 32, "fire_delay": 0.27, "reload_time": 2.05, "pellets": 8, "automatic": true, "fire_modes": ["auto"], "recoil_pattern": [Vector2(0.012, 0.052), Vector2(-0.016, 0.058), Vector2(0.018, 0.064)], "category": "auto_shotgun", "penetration_power": 0.32, "armor_penetration": 0.3, "ads_fov": 62.0, "shot_impulse": 6.2}),
		"marksman": Definition.create({"key": "marksman", "display_name": "MARKSMAN", "price": 3300, "damage": 82.0, "head_multiplier": 2.2, "spread": 0.004, "move_spread": 0.055, "range": 82.0, "magazine": 10, "reserve": 30, "fire_delay": 0.72, "reload_time": 1.8, "automatic": false, "fire_modes": ["semi"], "recoil_pattern": [Vector2(0.006, 0.055), Vector2(-0.008, 0.06)], "category": "dmr", "penetration_power": 1.55, "armor_penetration": 0.88, "ads_fov": 38.0, "falloff_start": 42.0, "falloff_end": 90.0, "shot_impulse": 6.0}),
		"heavy_sniper": Definition.create({"key": "heavy_sniper", "display_name": "HEAVY SNIPER", "price": 4700, "damage": 118.0, "head_multiplier": 2.0, "spread": 0.0015, "move_spread": 0.085, "range": 110.0, "magazine": 5, "reserve": 15, "fire_delay": 1.25, "reload_time": 2.25, "automatic": false, "fire_modes": ["bolt"], "recoil_pattern": [Vector2(0.0, 0.095)], "category": "sniper", "penetration_power": 2.2, "armor_penetration": 0.96, "ads_fov": 24.0, "falloff_start": 70.0, "falloff_end": 120.0, "minimum_damage_multiplier": 0.82, "shot_impulse": 9.0}),
		"bulwark": Definition.create({"key": "bulwark", "display_name": "BULWARK LMG", "price": 4200, "damage": 29.0, "head_multiplier": 3.0, "spread": 0.023, "move_spread": 0.065, "range": 62.0, "magazine": 60, "reserve": 120, "fire_delay": 0.085, "reload_time": 3.1, "recoil_pattern": [Vector2(-0.008, 0.022), Vector2(0.011, 0.024), Vector2(0.015, 0.027), Vector2(-0.018, 0.03), Vector2(0.02, 0.032)], "category": "lmg", "penetration_power": 1.08, "armor_penetration": 0.72, "ads_fov": 58.0, "weight": 1.38, "shot_impulse": 4.5}),
		"frag": Definition.create({"key": "frag", "display_name": "FRAG", "slot": Definition.Slot.GRENADE, "price": 300, "damage": 88.0, "range": 7.0, "magazine": 1, "reserve": 0, "fire_delay": 1.0, "reload_time": 0.0, "automatic": false, "fire_modes": ["throw"], "category": "frag"}),
		"smoke": Definition.create({"key": "smoke", "display_name": "SMOKE", "slot": Definition.Slot.GRENADE, "price": 300, "damage": 0.0, "range": 6.5, "magazine": 1, "reserve": 0, "fire_delay": 1.0, "reload_time": 0.0, "automatic": false, "fire_modes": ["throw"], "category": "smoke"}),
		"flash": Definition.create({"key": "flash", "display_name": "FLASH", "slot": Definition.Slot.GRENADE, "price": 250, "damage": 0.0, "range": 9.0, "magazine": 1, "reserve": 0, "fire_delay": 1.0, "reload_time": 0.0, "automatic": false, "fire_modes": ["throw"], "category": "flash"}),
		"incendiary": Definition.create({"key": "incendiary", "display_name": "INCENDIARY", "slot": Definition.Slot.GRENADE, "price": 450, "damage": 8.0, "range": 3.5, "magazine": 1, "reserve": 0, "fire_delay": 1.0, "reload_time": 0.0, "automatic": false, "fire_modes": ["throw"], "category": "incendiary"})
	}
